# Generated by Django 5.2.7 on 2025-10-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='eye_scans/')),
                ('condition_detected', models.CharField(choices=[('cataract', 'Cataract'), ('redness', 'Redness'), ('dryness', 'Dryness'), ('glaucoma', 'Glaucoma'), ('conjunctivitis', 'Conjunctivitis'), ('normal', 'Normal')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
