# Generated by Django 5.2.7 on 2025-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, help_text='Medical specialization (for specialists only)', max_length=100, null=True),
        ),
    ]
